spring:
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:10}
          max-idle: ${REDIS_POOL_MAX_IDLE:5}
          min-idle: ${REDIS_POOL_MIN_IDLE:2}
          max-wait: ${REDIS_POOL_MAX_WAIT:1000ms}
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: ${AUTH_SERVICE_URL}
            predicates:
              - Path=/api/auth/v1/**
server:
  port: 8080

app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
  gateway:
    public-routes:
      - /api/auth/v1/**

logging:
  level:
    root: INFO